import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

/**
 * Normalizes bbox data to the standard {x, y, w, h} object format.
 * Handles both array [x, y, w, h] and [x1, y1, x2, y2] formats,
 * as well as the expected {x, y, w, h} object format.
 */
function normalizeBBox(bbox: any): {
  x: number;
  y: number;
  w: number;
  h: number;
} {
  if (!bbox) return { x: 0, y: 0, w: 0, h: 0 };

  // Already in correct object format
  if (
    typeof bbox === "object" &&
    !Array.isArray(bbox) &&
    "x" in bbox &&
    "w" in bbox
  ) {
    return {
      x: Number(bbox.x) || 0,
      y: Number(bbox.y) || 0,
      w: Number(bbox.w) || 0,
      h: Number(bbox.h) || 0,
    };
  }

  // Array format [x, y, w, h]
  if (Array.isArray(bbox) && bbox.length >= 4) {
    const [v0, v1, v2, v3] = bbox.map(Number);
    // Heuristic: if v2 > v0 && v3 > v1, it's likely [x1, y1, x2, y2]
    if (v2 > v0 * 2 && v3 > v1 * 2) {
      return { x: v0, y: v1, w: v2 - v0, h: v3 - v1 };
    }
    return { x: v0, y: v1, w: v2, h: v3 };
  }

  return { x: 0, y: 0, w: 0, h: 0 };
}

/**
 * Normalizes a token object to ensure consistent field naming and bbox format.
 */
function normalizeToken(token: any, index: number): any {
  return {
    id: token.id || `token-${index}`,
    lineId: token.lineId || token.line_id || "",
    tokenNo: token.tokenNo ?? token.token_no ?? index,
    bbox: normalizeBBox(token.bbox),
    textOcr: token.textOcr ?? token.text_ocr ?? token.text ?? "",
    textVerified: token.textVerified ?? token.text_verified ?? null,
    confidence: typeof token.confidence === "number" ? token.confidence : 1.0,
    bboxHeuristic: token.bboxHeuristic ?? token.bbox_heuristic ?? false,
  };
}

/**
 * Normalizes a line object to ensure consistent field naming and bbox format.
 */
function normalizeLine(line: any, index: number): any {
  return {
    id: line.id || `line-${index}`,
    lineNo: line.lineNo ?? line.line_no ?? index,
    bbox: normalizeBBox(line.bbox),
    textOcr: line.textOcr ?? line.text_ocr ?? line.text ?? "",
  };
}

export async function GET(
  req: Request,
  { params }: { params: { id: string } },
) {
  try {
    const pageId = decodeURIComponent(params.id);

    const page = await prisma.page.findUnique({
      where: { id: pageId },
      include: { document: true },
    });

    if (!page) {
      return NextResponse.json({ error: "Page not found" }, { status: 404 });
    }

    // `assets` contains { lines, tokens } generated by Python script
    let assetsData: any = { lines: [], tokens: [] };
    if (page.assets) {
      try {
        assetsData =
          typeof page.assets === "string"
            ? JSON.parse(page.assets)
            : page.assets;
      } catch (e) {
        console.error("Failed to parse assets", e);
      }
    }

    // Normalize all tokens and lines to standard format
    const normalizedTokens = (assetsData.tokens || []).map(normalizeToken);
    const normalizedLines = (assetsData.lines || []).map(normalizeLine);

    return NextResponse.json({
      page: {
        id: page.id,
        documentId: page.documentId,
        pageNo: page.pageNo,
        status: page.needsReview ? "ocr" : "verified",
        needsReview: page.needsReview,
        risky: page.needsReview,
        imageUrl: page.imageUrl,
        width: page.width,
        height: page.height,
      },
      image: {
        signedUrl: page.imageUrl,
        width: page.width,
        height: page.height,
      },
      lines: normalizedLines,
      tokens: normalizedTokens,
      patchSummary: {
        risky: false,
        needsReview: page.needsReview,
        totalOps: 0,
      },
    });
  } catch (error) {
    console.error("Error fetching page assets:", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}
